module Kuby::CRDB::DSL::CRDB::V1alpha1
  autoload :Status, 'kuby/crdb/dsl/crdb/v1alpha1/status'
  autoload :SpecImage, 'kuby/crdb/dsl/crdb/v1alpha1/spec_image'
  autoload :SpecAffinityPodAffinity, 'kuby/crdb/dsl/crdb/v1alpha1/spec_affinity_pod_affinity'
  autoload :SpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution, 'kuby/crdb/dsl/crdb/v1alpha1/spec_affinity_node_affinity_required_during_scheduling_ignored_during_execution'
  autoload :SpecAffinityNodeAffinity, 'kuby/crdb/dsl/crdb/v1alpha1/spec_affinity_node_affinity'
  autoload :SpecAffinityPodAntiAffinity, 'kuby/crdb/dsl/crdb/v1alpha1/spec_affinity_pod_anti_affinity'
  autoload :SpecAffinity, 'kuby/crdb/dsl/crdb/v1alpha1/spec_affinity'
  autoload :SpecResources, 'kuby/crdb/dsl/crdb/v1alpha1/spec_resources'
  autoload :SpecDataStorePvcSource, 'kuby/crdb/dsl/crdb/v1alpha1/spec_data_store_pvc_source'
  autoload :SpecDataStorePvcSpecSelector, 'kuby/crdb/dsl/crdb/v1alpha1/spec_data_store_pvc_spec_selector'
  autoload :SpecDataStorePvcSpecDataSource, 'kuby/crdb/dsl/crdb/v1alpha1/spec_data_store_pvc_spec_data_source'
  autoload :SpecDataStorePvcSpecResources, 'kuby/crdb/dsl/crdb/v1alpha1/spec_data_store_pvc_spec_resources'
  autoload :SpecDataStorePvcSpec, 'kuby/crdb/dsl/crdb/v1alpha1/spec_data_store_pvc_spec'
  autoload :SpecDataStorePvc, 'kuby/crdb/dsl/crdb/v1alpha1/spec_data_store_pvc'
  autoload :SpecDataStoreHostPath, 'kuby/crdb/dsl/crdb/v1alpha1/spec_data_store_host_path'
  autoload :SpecDataStore, 'kuby/crdb/dsl/crdb/v1alpha1/spec_data_store'
  autoload :Spec, 'kuby/crdb/dsl/crdb/v1alpha1/spec'
  autoload :CrdbClusterList, 'kuby/crdb/dsl/crdb/v1alpha1/crdb_cluster_list'
  autoload :CrdbCluster, 'kuby/crdb/dsl/crdb/v1alpha1/crdb_cluster'
end
